using Jacobi.Zim80.Components.CpuZ80.States.Instructions;

namespace Jacobi.Zim80.Components.CpuZ80.Opcodes
{
    partial class OpcodeDefinition
    {
        public static readonly OpcodeDefinition[] Defintions = new OpcodeDefinition[]
        {
            // X = 0
            new OpcodeDefinition { X = 0, Z = 0, Y = 0, Text = "NOP", Cycles = new[] { 4 }, Instruction = typeof(NopInstruction) },
            new OpcodeDefinition { X = 0, Z = 0, Y = 1, Text = "EX AF, AF'", Cycles = new[] { 4 }, Instruction = typeof(ExAFAFInstruction) },
            new OpcodeDefinition { X = 0, Z = 0, Y = 2, Text = "DJNZ {0}", d = true, Cycles = new[] { 5, 3, 5 }, AltCycles = new[] { 5, 3 }, Instruction = typeof(DjnzInstruction) },
            new OpcodeDefinition { X = 0, Z = 0, Y = 3, Text = "JR {0}", d = true, Cycles = new[] { 4, 3, 5 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 4, Text = "JR NZ, {0}", d = true, Cycles = new[] { 4, 3, 5 }, AltCycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 5, Text = "JR Z, {0}", d = true, Cycles = new[] { 4, 3, 5 }, AltCycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 6, Text = "JR NC, {0}", d = true, Cycles = new[] { 4, 3, 5 }, AltCycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 7, Text = "JR C, {0}", d = true, Cycles = new[] { 4, 3, 5 }, AltCycles = new[] { 4, 3 } },

            new OpcodeDefinition { X = 0, Z = 1, Q = 0, P = 0, Text = "LD BC, {0}", nn = true, Cycles = new[] { 4, 3, 3 }, Instruction = typeof(LoadImmediate16Instruction) },
            new OpcodeDefinition { X = 0, Z = 1, Q = 0, P = 1, Text = "LD DE, {0}", nn = true, Cycles = new[] { 4, 3, 3 }, Instruction = typeof(LoadImmediate16Instruction) },
            new OpcodeDefinition { X = 0, Z = 1, Q = 0, P = 2, Text = "LD HL, {0}", nn = true, Cycles = new[] { 4, 3, 3 }, Instruction = typeof(LoadImmediate16Instruction) },
            new OpcodeDefinition { X = 0, Z = 1, Q = 0, P = 3, Text = "LD SP, {0}", nn = true, Cycles = new[] { 4, 3, 3 }, Instruction = typeof(LoadImmediate16Instruction) },
            new OpcodeDefinition { X = 0, Z = 1, Q = 1, P = 0, Text = "ADD HL, BC", Cycles = new[] { 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 1, Q = 1, P = 1, Text = "ADD HL, DE", Cycles = new[] { 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 1, Q = 1, P = 2, Text = "ADD HL, HL", Cycles = new[] { 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 1, Q = 1, P = 3, Text = "ADD HL, SP", Cycles = new[] { 4, 4, 3 } },

            new OpcodeDefinition { X = 0, Z = 2, Q = 0, P = 0, Text = "LD (BC), A", Cycles = new[] { 4, 3 }, Instruction = typeof(WriteIndirectRegisterInstruction) },
            new OpcodeDefinition { X = 0, Z = 2, Q = 0, P = 1, Text = "LD (DE), A", Cycles = new[] { 4, 3 }, Instruction = typeof(WriteIndirectRegisterInstruction) },
            new OpcodeDefinition { X = 0, Z = 2, Q = 0, P = 2, Text = "LD ({0}), HL", nn = true, Cycles = new[] { 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 0, Z = 2, Q = 0, P = 3, Text = "LD ({0}), A", nn = true, Cycles = new[] { 4, 3, 3, 3 } },
            new OpcodeDefinition { X = 0, Z = 2, Q = 1, P = 0, Text = "LD A, (BC)", Cycles = new[] { 4, 3 }, Instruction = typeof(ReadIndirectRegisterInstruction) },
            new OpcodeDefinition { X = 0, Z = 2, Q = 1, P = 1, Text = "LD A, (DE)", Cycles = new[] { 4, 3 }, Instruction = typeof(ReadIndirectRegisterInstruction) },
            new OpcodeDefinition { X = 0, Z = 2, Q = 1, P = 2, Text = "LD HL, ({0})", nn = true, Cycles = new[] { 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 0, Z = 2, Q = 1, P = 3, Text = "LD A, ({0})", nn = true, Cycles = new[] { 4, 3, 3, 3 } },

            new OpcodeDefinition { X = 0, Z = 3, Q = 0, P = 0, Text = "INC BC", Cycles = new[] { 6 }, Instruction = typeof(Inc16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 0, P = 1, Text = "INC DE", Cycles = new[] { 6 }, Instruction = typeof(Inc16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 0, P = 2, Text = "INC HL", Cycles = new[] { 6 }, Instruction = typeof(Inc16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 0, P = 3, Text = "INC SP", Cycles = new[] { 6 }, Instruction = typeof(Inc16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 1, P = 0, Text = "DEC BC", Cycles = new[] { 6 }, Instruction = typeof(Dec16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 1, P = 1, Text = "DEC DE", Cycles = new[] { 6 }, Instruction = typeof(Dec16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 1, P = 2, Text = "DEC HL", Cycles = new[] { 6 }, Instruction = typeof(Dec16Instruction) },
            new OpcodeDefinition { X = 0, Z = 3, Q = 1, P = 3, Text = "DEC SP", Cycles = new[] { 6 }, Instruction = typeof(Dec16Instruction) },

            new OpcodeDefinition { X = 0, Z = 4, Y = 0, Text = "INC B", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },
            new OpcodeDefinition { X = 0, Z = 4, Y = 1, Text = "INC C", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },
            new OpcodeDefinition { X = 0, Z = 4, Y = 2, Text = "INC D", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },
            new OpcodeDefinition { X = 0, Z = 4, Y = 3, Text = "INC E", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },
            new OpcodeDefinition { X = 0, Z = 4, Y = 4, Text = "INC H", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },
            new OpcodeDefinition { X = 0, Z = 4, Y = 5, Text = "INC L", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },
            new OpcodeDefinition { X = 0, Z = 4, Y = 6, Text = "INC (HL)", Cycles = new[] { 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 7, Text = "INC A", Cycles = new[] { 4 }, Instruction = typeof(Inc8Instruction) },

            new OpcodeDefinition { X = 0, Z = 5, Y = 0, Text = "DEC B", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },
            new OpcodeDefinition { X = 0, Z = 5, Y = 1, Text = "DEC C", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },
            new OpcodeDefinition { X = 0, Z = 5, Y = 2, Text = "DEC D", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },
            new OpcodeDefinition { X = 0, Z = 5, Y = 3, Text = "DEC E", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },
            new OpcodeDefinition { X = 0, Z = 5, Y = 4, Text = "DEC H", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },
            new OpcodeDefinition { X = 0, Z = 5, Y = 5, Text = "DEC L", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },
            new OpcodeDefinition { X = 0, Z = 5, Y = 6, Text = "DEC (HL)", Cycles = new[] { 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 7, Text = "DEC A", Cycles = new[] { 4 }, Instruction = typeof(Dec8Instruction) },

            new OpcodeDefinition { X = 0, Z = 6, Y = 0, Text = "LD B, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },
            new OpcodeDefinition { X = 0, Z = 6, Y = 1, Text = "LD C, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },
            new OpcodeDefinition { X = 0, Z = 6, Y = 2, Text = "LD D, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },
            new OpcodeDefinition { X = 0, Z = 6, Y = 3, Text = "LD E, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },
            new OpcodeDefinition { X = 0, Z = 6, Y = 4, Text = "LD H, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },
            new OpcodeDefinition { X = 0, Z = 6, Y = 5, Text = "LD L, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },
            new OpcodeDefinition { X = 0, Z = 6, Y = 6, Text = "LD (HL), {0}", n = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 7, Text = "LD A, {0}", n = true, Cycles = new[] { 4, 3 }, Instruction = typeof(LoadImmediate8Instruction) },

            new OpcodeDefinition { X = 0, Z = 7, Y = 0, Text = "RLCA", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 1, Text = "RRCA", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 2, Text = "RLA", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 3, Text = "RRA", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 4, Text = "DAA", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 5, Text = "CPL", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 6, Text = "SCF", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 7, Text = "CCF", Cycles = new[] { 4 } },

            // X = 1
            new OpcodeDefinition { X = 1, Z = 0, Y = 0, Text = "LD B, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 1, Text = "LD C, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 2, Text = "LD D, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 3, Text = "LD E, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 4, Text = "LD H, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 5, Text = "LD L, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 6, Text = "LD (HL), B", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 7, Text = "LD A, B", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 1, Z = 1, Y = 0, Text = "LD B, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 1, Text = "LD C, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 2, Text = "LD D, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 3, Text = "LD E, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 4, Text = "LD H, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 5, Text = "LD L, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 6, Text = "LD (HL), C", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 7, Text = "LD A, C", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 1, Z = 2, Y = 0, Text = "LD B, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 1, Text = "LD C, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 2, Text = "LD D, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 3, Text = "LD E, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 4, Text = "LD H, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 5, Text = "LD L, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 6, Text = "LD (HL), D", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 7, Text = "LD A, D", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 1, Z = 3, Y = 0, Text = "LD B, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 1, Text = "LD C, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 2, Text = "LD D, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 3, Text = "LD E, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 4, Text = "LD H, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 5, Text = "LD L, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 6, Text = "LD (HL), E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 7, Text = "LD A, E", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 1, Z = 4, Y = 0, Text = "LD B, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 1, Text = "LD C, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 2, Text = "LD D, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 3, Text = "LD E, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 4, Text = "LD H, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 5, Text = "LD L, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 6, Text = "LD (HL), H", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 7, Text = "LD A, H", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 1, Z = 5, Y = 0, Text = "LD B, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 1, Text = "LD C, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 2, Text = "LD D, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 3, Text = "LD E, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 4, Text = "LD H, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 5, Text = "LD L, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 6, Text = "LD (HL), L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 7, Text = "LD A, L", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 1, Z = 6, Y = 0, Text = "LD B, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 1, Text = "LD C, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 2, Text = "LD D, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 3, Text = "LD E, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 4, Text = "LD H, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 5, Text = "LD L, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 6, Text = "HALT", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 7, Text = "LD A, (HL)", Cycles = new[] { 4, 3 } },

            new OpcodeDefinition { X = 1, Z = 7, Y = 0, Text = "LD B, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 1, Text = "LD C, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 2, Text = "LD D, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 3, Text = "LD E, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 4, Text = "LD H, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 5, Text = "LD L, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 6, Text = "LD (HL), A", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 7, Text = "LD A, A", Cycles = new[] { 4 } },

            // X = 2
            new OpcodeDefinition { X = 2, Z = 0, Y = 0, Text = "ADD A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 1, Text = "ADC A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 2, Text = "SUB A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 3, Text = "SBC A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 4, Text = "AND A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 5, Text = "XOR A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 6, Text = "OR A, B", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 7, Text = "CP A, B", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 2, Z = 1, Y = 0, Text = "ADD A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 1, Text = "ADC A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 2, Text = "SUB A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 3, Text = "SBC A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 4, Text = "AND A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 5, Text = "XOR A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 6, Text = "OR A, C", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 7, Text = "CP A, C", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 2, Z = 2, Y = 0, Text = "ADD A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 1, Text = "ADC A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 2, Text = "SUB A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 3, Text = "SBC A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 4, Text = "AND A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 5, Text = "XOR A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 6, Text = "OR A, D", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 7, Text = "CP A, D", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 2, Z = 3, Y = 0, Text = "ADD A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 1, Text = "ADC A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 2, Text = "SUB A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 3, Text = "SBC A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 4, Text = "AND A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 5, Text = "XOR A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 6, Text = "OR A, E", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 7, Text = "CP A, E", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 2, Z = 4, Y = 0, Text = "ADD A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 1, Text = "ADC A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 2, Text = "SUB A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 3, Text = "SBC A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 4, Text = "AND A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 5, Text = "XOR A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 6, Text = "OR A, H", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 7, Text = "CP A, H", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 2, Z = 5, Y = 0, Text = "ADD A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 1, Text = "ADC A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 2, Text = "SUB A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 3, Text = "SBC A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 4, Text = "AND A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 5, Text = "XOR A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 6, Text = "OR A, L", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 7, Text = "CP A, L", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 2, Z = 6, Y = 0, Text = "ADD A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 1, Text = "ADC A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 2, Text = "SUB A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 3, Text = "SBC A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 4, Text = "AND A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 5, Text = "XOR A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 6, Text = "OR A, (HL)", Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 7, Text = "CP A, (HL)", Cycles = new[] { 4, 3 } },

            new OpcodeDefinition { X = 2, Z = 7, Y = 0, Text = "ADD A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 1, Text = "ADC A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 2, Text = "SUB A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 3, Text = "SBC A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 4, Text = "AND A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 5, Text = "XOR A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 6, Text = "OR A, A", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 7, Text = "CP A, A", Cycles = new[] { 4 } },

            // X = 3
            new OpcodeDefinition { X = 3, Z = 0, Y = 0, Text = "RET NZ", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 1, Text = "RET Z", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 2, Text = "RET NC", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 3, Text = "RET C", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 4, Text = "RET PO", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 5, Text = "RET PE", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 6, Text = "RET P", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 7, Text = "RET M", Cycles = new[] { 5, 3, 3 }, AltCycles = new[] { 5 } },

            new OpcodeDefinition { X = 3, Z = 1, Q = 0, P = 0, Text = "POP BC", Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 0, P = 1, Text = "POP DE", Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 0, P = 2, Text = "POP HL", Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 0, P = 3, Text = "POP AF", Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 1, P = 0, Text = "RET", Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 1, P = 1, Text = "EXX", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 1, P = 2, Text = "JP HL", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Q = 1, P = 3, Text = "LD SP, HL", Cycles = new[] { 6 } },

            new OpcodeDefinition { X = 3, Z = 2, Y = 0, Text = "JP NZ, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 1, Text = "JP Z, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 2, Text = "JP NC, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 3, Text = "JP C, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 4, Text = "JP PO, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 5, Text = "JP PE, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 6, Text = "JP P, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 7, Text = "JP M, {0}", nn = true, Cycles = new[] { 4, 3, 3 } },

            new OpcodeDefinition { X = 3, Z = 3, Y = 0, Text = "JP {0}", nn = true, Cycles = new[] { 4, 3, 3 } },
            //new OpcodeDefinition { X = 3, Z = 3, Y = 1, Text = "#CB", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 2, Text = "OUT ({0}), A", n = true, Cycles = new[] { 4, 4 } },    //Cycles?
            new OpcodeDefinition { X = 3, Z = 3, Y = 3, Text = "IN A,({0})", n = true, Cycles = new[] { 4, 4 } },      //Cycles?
            new OpcodeDefinition { X = 3, Z = 3, Y = 4, Text = "EX (SP), HL", Cycles = new[] { 4, 3, 4, 3, 5 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 5, Text = "EX DE, HL", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 6, Text = "DI", Cycles = new[] { 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 7, Text = "EI", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 3, Z = 4, Y = 0, Text = "CALL NZ, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 1, Text = "CALL Z, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 2, Text = "CALL NC, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 3, Text = "CALL C, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 4, Text = "CALL PO, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 5, Text = "CALL PE, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 6, Text = "CALL P, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 7, Text = "CALL M, {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 }, AltCycles = new[] { 4, 3, 3 } },

            new OpcodeDefinition { X = 3, Z = 5, Q = 0, P = 0, Text = "PUSH BC", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 5, Q = 0, P = 1, Text = "PUSH DE", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 5, Q = 0, P = 2, Text = "PUSH HL", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 5, Q = 0, P = 3, Text = "PUSH AF", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 5, Q = 1, P = 0, Text = "CALL {0}", nn = true, Cycles = new[] { 4, 3, 4, 3, 3 } },
            //new OpcodeDefinition { X = 3, Z = 5, Q = 1, P = 1, Text = "#DD", Cycles = new[] { 4 } },
            //new OpcodeDefinition { X = 3, Z = 5, Q = 1, P = 2, Text = "#ED", Cycles = new[] { 4 } },
            //new OpcodeDefinition { X = 3, Z = 5, Q = 1, P = 3, Text = "#FD", Cycles = new[] { 4 } },

            new OpcodeDefinition { X = 3, Z = 6, Y = 0, Text = "ADD A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 1, Text = "ADC A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 2, Text = "SUB A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 3, Text = "SBC A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 4, Text = "AND A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 5, Text = "XOR A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 6, Text = "OR A, {0}", n = true, Cycles = new[] { 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 7, Text = "CP A, {0}", n = true, Cycles = new[] { 4, 3 } },

            new OpcodeDefinition { X = 3, Z = 7, Y = 0, Text = "RST 00", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 1, Text = "RST 08", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 2, Text = "RST 10", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 3, Text = "RST 18", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 4, Text = "RST 20", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 5, Text = "RST 28", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 6, Text = "RST 30", Cycles = new[] { 5, 3, 3 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 7, Text = "RST 38", Cycles = new[] { 5, 3, 3 } },

            // CB prefixed
            // X = 0
            new OpcodeDefinition { X = 0, Z = 0, Y = 0, Text = "RLC B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 1, Text = "RRC B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 2, Text = "RL B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 3, Text = "RR B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 4, Text = "SLA B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 5, Text = "SRA B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 6, Text = "SLL B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 0, Y = 7, Text = "SRL B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 0, Z = 1, Y = 0, Text = "RLC C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 1, Text = "RRC C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 2, Text = "RL C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 3, Text = "RR C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 4, Text = "SLA C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 5, Text = "SRA C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 6, Text = "SLL C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 1, Y = 7, Text = "SRL C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 0, Z = 2, Y = 0, Text = "RLC D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 1, Text = "RRC D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 2, Text = "RL D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 3, Text = "RR D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 4, Text = "SLA D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 5, Text = "SRA D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 6, Text = "SLL D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 2, Y = 7, Text = "SRL D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 0, Z = 3, Y = 0, Text = "RLC E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 1, Text = "RRC E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 2, Text = "RL E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 3, Text = "RR E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 4, Text = "SLA E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 5, Text = "SRA E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 6, Text = "SLL E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 3, Y = 7, Text = "SRL E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 0, Z = 4, Y = 0, Text = "RLC H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 1, Text = "RRC H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 2, Text = "RL H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 3, Text = "RR H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 4, Text = "SLA H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 5, Text = "SRA H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 6, Text = "SLL H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 4, Y = 7, Text = "SRL H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 0, Z = 5, Y = 0, Text = "RLC L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 1, Text = "RRC L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 2, Text = "RL L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 3, Text = "RR L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 4, Text = "SLA L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 5, Text = "SRA L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 6, Text = "SLL L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 5, Y = 7, Text = "SRL L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 0, Z = 6, Y = 0, Text = "RLC (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 1, Text = "RRC (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 2, Text = "RL (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 3, Text = "RR (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 4, Text = "SLA (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 5, Text = "SRA (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 6, Text = "SLL (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 0, Z = 6, Y = 7, Text = "SRL (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },

            new OpcodeDefinition { X = 0, Z = 7, Y = 0, Text = "RLC A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 1, Text = "RRC A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 2, Text = "RL A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 3, Text = "RR A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 4, Text = "SLA A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 5, Text = "SRA A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 6, Text = "SLL A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 0, Z = 7, Y = 7, Text = "SRL A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            // X = 1
            new OpcodeDefinition { X = 1, Z = 0, Y = 0, Text = "BIT 0, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 1, Text = "BIT 1, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 2, Text = "BIT 2, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 3, Text = "BIT 3, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 4, Text = "BIT 4, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 5, Text = "BIT 5, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 6, Text = "BIT 6, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 7, Text = "BIT 7, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 1, Y = 0, Text = "BIT 0, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 1, Text = "BIT 1, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 2, Text = "BIT 2, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 3, Text = "BIT 3, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 4, Text = "BIT 4, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 5, Text = "BIT 5, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 6, Text = "BIT 6, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 7, Text = "BIT 7, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 2, Y = 0, Text = "BIT 0, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 1, Text = "BIT 1, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 2, Text = "BIT 2, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 3, Text = "BIT 3, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 4, Text = "BIT 4, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 5, Text = "BIT 5, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 6, Text = "BIT 6, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 2, Y = 7, Text = "BIT 7, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 3, Y = 0, Text = "BIT 0, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 1, Text = "BIT 1, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 2, Text = "BIT 2, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 3, Text = "BIT 3, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 4, Text = "BIT 4, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 5, Text = "BIT 5, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 6, Text = "BIT 6, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 3, Y = 7, Text = "BIT 7, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 4, Y = 0, Text = "BIT 0, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 1, Text = "BIT 1, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 2, Text = "BIT 2, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 3, Text = "BIT 3, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 4, Text = "BIT 4, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 5, Text = "BIT 5, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 6, Text = "BIT 6, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 4, Y = 7, Text = "BIT 7, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 5, Y = 0, Text = "BIT 0, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 1, Text = "BIT 1, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 2, Text = "BIT 2, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 3, Text = "BIT 3, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 4, Text = "BIT 4, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 5, Text = "BIT 5, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 6, Text = "BIT 6, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 7, Text = "BIT 7, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 6, Y = 0, Text = "BIT 0, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 1, Text = "BIT 1, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 2, Text = "BIT 2, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 3, Text = "BIT 3, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 4, Text = "BIT 4, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 5, Text = "BIT 5, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 6, Text = "BIT 6, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 7, Text = "BIT 7, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 7, Y = 0, Text = "BIT 0, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 1, Text = "BIT 1, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 2, Text = "BIT 2, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 3, Text = "BIT 3, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 4, Text = "BIT 4, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 5, Text = "BIT 5, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 6, Text = "BIT 6, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 7, Text = "BIT 7, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            // X = 2
            new OpcodeDefinition { X = 2, Z = 0, Y = 0, Text = "RES 0, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 1, Text = "RES 1, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 2, Text = "RES 2, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 3, Text = "RES 3, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 4, Text = "RES 4, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 5, Text = "RES 5, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 6, Text = "RES 6, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 7, Text = "RES 7, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 2, Z = 1, Y = 0, Text = "RES 0, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 1, Text = "RES 1, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 2, Text = "RES 2, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 3, Text = "RES 3, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 4, Text = "RES 4, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 5, Text = "RES 5, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 6, Text = "RES 6, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 7, Text = "RES 7, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 2, Z = 2, Y = 0, Text = "RES 0, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 1, Text = "RES 1, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 2, Text = "RES 2, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 3, Text = "RES 3, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 4, Text = "RES 4, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 5, Text = "RES 5, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 6, Text = "RES 6, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 7, Text = "RES 7, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 2, Z = 3, Y = 0, Text = "RES 0, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 1, Text = "RES 1, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 2, Text = "RES 2, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 3, Text = "RES 3, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 4, Text = "RES 4, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 5, Text = "RES 5, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 6, Text = "RES 6, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 7, Text = "RES 7, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 2, Z = 4, Y = 0, Text = "RES 0, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 1, Text = "RES 1, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 2, Text = "RES 2, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 3, Text = "RES 3, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 4, Text = "RES 4, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 5, Text = "RES 5, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 6, Text = "RES 6, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 4, Y = 7, Text = "RES 7, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 2, Z = 5, Y = 0, Text = "RES 0, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 1, Text = "RES 1, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 2, Text = "RES 2, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 3, Text = "RES 3, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 4, Text = "RES 4, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 5, Text = "RES 5, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 6, Text = "RES 6, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 5, Y = 7, Text = "RES 7, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 2, Z = 6, Y = 0, Text = "RES 0, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 1, Text = "RES 1, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 2, Text = "RES 2, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 3, Text = "RES 3, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 4, Text = "RES 4, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 5, Text = "RES 5, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 6, Text = "RES 6, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 2, Z = 6, Y = 7, Text = "RES 7, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },

            new OpcodeDefinition { X = 2, Z = 7, Y = 0, Text = "RES 0, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 1, Text = "RES 1, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 2, Text = "RES 2, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 3, Text = "RES 3, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 4, Text = "RES 4, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 5, Text = "RES 5, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 6, Text = "RES 6, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 2, Z = 7, Y = 7, Text = "RES 7, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            // X = 3
            new OpcodeDefinition { X = 3, Z = 0, Y = 0, Text = "SET 0, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 1, Text = "SET 1, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 2, Text = "SET 2, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 3, Text = "SET 3, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 4, Text = "SET 4, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 5, Text = "SET 5, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 6, Text = "SET 6, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 0, Y = 7, Text = "SET 7, B", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 3, Z = 1, Y = 0, Text = "SET 0, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 1, Text = "SET 1, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 2, Text = "SET 2, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 3, Text = "SET 3, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 4, Text = "SET 4, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 5, Text = "SET 5, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 6, Text = "SET 6, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 1, Y = 7, Text = "SET 7, C", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 3, Z = 2, Y = 0, Text = "SET 0, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 1, Text = "SET 1, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 2, Text = "SET 2, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 3, Text = "SET 3, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 4, Text = "SET 4, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 5, Text = "SET 5, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 6, Text = "SET 6, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 2, Y = 7, Text = "SET 7, D", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 3, Z = 3, Y = 0, Text = "SET 0, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 1, Text = "SET 1, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 2, Text = "SET 2, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 3, Text = "SET 3, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 4, Text = "SET 4, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 5, Text = "SET 5, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 6, Text = "SET 6, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 3, Y = 7, Text = "SET 7, E", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 3, Z = 4, Y = 0, Text = "SET 0, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 1, Text = "SET 1, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 2, Text = "SET 2, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 3, Text = "SET 3, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 4, Text = "SET 4, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 5, Text = "SET 5, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 6, Text = "SET 6, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 4, Y = 7, Text = "SET 7, H", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 3, Z = 5, Y = 0, Text = "SET 0, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 1, Text = "SET 1, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 2, Text = "SET 2, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 3, Text = "SET 3, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 4, Text = "SET 4, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 5, Text = "SET 5, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 6, Text = "SET 6, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 5, Y = 7, Text = "SET 7, L", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 3, Z = 6, Y = 0, Text = "SET 0, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 1, Text = "SET 1, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 2, Text = "SET 2, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 3, Text = "SET 3, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 4, Text = "SET 4, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 5, Text = "SET 5, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 6, Text = "SET 6, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 3, Z = 6, Y = 7, Text = "SET 7, (HL)", Ext1 = 0xCB, Cycles = new[] { 4, 4, 4, 3 } },

            new OpcodeDefinition { X = 3, Z = 7, Y = 0, Text = "SET 0, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 1, Text = "SET 1, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 2, Text = "SET 2, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 3, Text = "SET 3, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 4, Text = "SET 4, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 5, Text = "SET 5, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 6, Text = "SET 6, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 3, Z = 7, Y = 7, Text = "SET 7, A", Ext1 = 0xCB, Cycles = new[] { 4, 4 } },

            // ED prefixed
            // X = 1
            new OpcodeDefinition { X = 1, Z = 0, Y = 0, Text = "IN B, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 1, Text = "IN C, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 2, Text = "IN D, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 3, Text = "IN E, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 4, Text = "IN H, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 5, Text = "IN L, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 0, Y = 6, Text = "IN (C)", Ext1 = 0xED, Cycles = new[] { 4, 4 } },    // cycles?
            new OpcodeDefinition { X = 1, Z = 0, Y = 7, Text = "IN A, (C)", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 1, Y = 0, Text = "OUT (C), B", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 1, Text = "OUT (C), C", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 2, Text = "OUT (C), D", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 3, Text = "OUT (C), E", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 4, Text = "OUT (C), H", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 5, Text = "OUT (C), L", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 1, Y = 6, Text = "OUT (C), 0", Ext1 = 0xED, Cycles = new[] { 4, 4 } },    // cycles?
            new OpcodeDefinition { X = 1, Z = 1, Y = 7, Text = "OUT (C), A", Ext1 = 0xED, Cycles = new[] { 4, 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 2, Q = 0, P = 0, Text = "SBC HL, BC", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 0, P = 1, Text = "SBC HL, DE", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 0, P = 2, Text = "SBC HL, HL", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 0, P = 3, Text = "SBC HL, SP", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 1, P = 0, Text = "ADC HL, BC", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 1, P = 1, Text = "ADC HL, DE", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 1, P = 2, Text = "ADC HL, HL", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 2, Q = 1, P = 3, Text = "ADC HL, SP", Ext1 = 0xED, Cycles = new[] { 4, 4, 4, 3 } },

            new OpcodeDefinition { X = 1, Z = 3, Q = 0, P = 0, Text = "LD ({0}), BC", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 0, P = 1, Text = "LD ({0}), DE", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 0, P = 2, Text = "LD ({0}), HL", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 0, P = 3, Text = "LD ({0}), SP", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 1, P = 0, Text = "LD BC, ({0})", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 1, P = 1, Text = "LD DE, ({0})", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 1, P = 2, Text = "LD HL, ({0})", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 3, Q = 1, P = 3, Text = "LD SP, ({0})", nn = true, Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3, 3, 3 } },

            new OpcodeDefinition { X = 1, Z = 4, Y = 0, Text = "NEG", Ext1 = 0xED, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 5, Y = 0, Text = "RETN", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 1, Text = "RETI", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 2, Text = "RETN", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 3, Text = "RETN", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 4, Text = "RETN", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 5, Text = "RETN", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },
            new OpcodeDefinition { X = 1, Z = 5, Y = 6, Text = "RETN", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 3 } },

            new OpcodeDefinition { X = 1, Z = 6, Y = 0, Text = "IM 0", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 1, Text = "IM 0/1", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 2, Text = "IM 1", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 3, Text = "IM 2", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 4, Text = "IM 0", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 5, Text = "IM 0/1", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 6, Text = "IM 1", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 6, Y = 7, Text = "IM 2", Ext1 = 0xED, Cycles = new[] { 4, 4 } },

            new OpcodeDefinition { X = 1, Z = 7, Y = 0, Text = "LD I, A", Ext1 = 0xED, Cycles = new[] { 4, 5 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 1, Text = "LD R, A", Ext1 = 0xED, Cycles = new[] { 4, 5 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 2, Text = "LD A, I", Ext1 = 0xED, Cycles = new[] { 4, 5 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 3, Text = "LD A, R", Ext1 = 0xED, Cycles = new[] { 4, 5 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 4, Text = "RRD", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 5, Text = "RLD", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 4, 3 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 6, Text = "NOP*", Ext1 = 0xED, Cycles = new[] { 4, 4 } },
            new OpcodeDefinition { X = 1, Z = 7, Y = 7, Text = "NOP*", Ext1 = 0xED, Cycles = new[] { 4, 4 } },

            // X = 2
            new OpcodeDefinition { X = 2, Z = 0, Y = 4, Text = "LDI", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 5, Text = "LDD", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 6, Text = "LDIR", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5, 5 } },
            new OpcodeDefinition { X = 2, Z = 0, Y = 7, Text = "LDDR", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5, 5 } },

            new OpcodeDefinition { X = 2, Z = 1, Y = 4, Text = "CPI", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 5, Text = "CPD", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 6, Text = "CPIR", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5, 5 }, AltCycles = new[] { 4, 4, 3, 5 } },
            new OpcodeDefinition { X = 2, Z = 1, Y = 7, Text = "CPDR", Ext1 = 0xED, Cycles = new[] { 4, 4, 3, 5, 5 }, AltCycles = new[] { 4, 4, 3, 5 } },

            new OpcodeDefinition { X = 2, Z = 2, Y = 4, Text = "INI", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 5, Text = "IND", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 6, Text = "INIR", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4, 5 }, AltCycles = new[] { 4, 5, 3, 4 } },
            new OpcodeDefinition { X = 2, Z = 2, Y = 7, Text = "INDR", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4, 5 }, AltCycles = new[] { 4, 5, 3, 4 } },

            new OpcodeDefinition { X = 2, Z = 3, Y = 4, Text = "OUTI", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 5, Text = "OUTD", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 6, Text = "OUTIR", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4, 5 }, AltCycles = new[] { 4, 5, 3, 4 } },
            new OpcodeDefinition { X = 2, Z = 3, Y = 7, Text = "OUTDR", Ext1 = 0xED, Cycles = new[] { 4, 5, 3, 4, 5 }, AltCycles = new[] { 4, 5, 3, 4 } },

            // DD-CB prefixed
            // X = 0

            // FD-CB prefixed
            // X = 0

        };
    }
}
